services:
  backend:
    build: 
      context: ./stock_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/stock_db
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db

  frontend:
    build:
      context: ./stock_frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=stock_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 